#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;
use JNCampbell\Scaffolder\CreatePackageCommand;

require 'vendor/autoload.php';

$app = new Application("Scaffolder", "1.0.0");

$app->add(new CreatePackageCommand);

$app->run();