#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;
use JNCampbell\Scaffolder\CreatePackageCommand;

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Application("Scaffolder", "1.0.0");

$app->add(new CreatePackageCommand);

$app->run();